name: task_bee
description: "TaskBee, görevlerinizi düzenlemenize ve işlerinizi halletmenize yardımcı olan bir görev yönetimi uygulamasıdır."
version: 1.0.0



environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  cloud_firestore: ^5.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true